export const OfferActionsType = {
  FETCH_OFFER_START: 'FETCH_OFFER_START',
  FETCH_OFFER_SUCCESS: 'FETCH_OFFER_SUCCESS',
  FETCH_OFFER_FAILURE: 'FETCH_OFFER_FAILURE',
  OFFER_INITIAL_ERRORS_STATE: 'OFFER_INITIAL_ERRORS_STATE',
};
